#!/usr/local/bin/perl
##
##  printenv -- demo CGI program which just prints its environment
##

print "Content-Type: text/html\n\n";
print "<html><body>";
foreach $var (sort(keys(%ENV))) {
    $val = $ENV{$var};
    $val =~ s|\n|\\n|g;
    $val =~ s|"|\\"|g;
    print "${var}=\"${val}\"\n";
}
print "</body></html>";
